#!/usr/bin/env bash
export RLBOT_WS_DIR=/home/mgiglia/workspaces/rlbot_ws
echo $1
export RLBOT_PKG_DIR=/home/mgiglia/workspaces/rlbot_ws/src/rlbot_bridge_pkg
export RLBOT_AGENT_DIR=/home/mgiglia/workspaces/rlbot_ws/src/rlbot_bridge_pkg/rlbot_bridge_pkg
echo $RL_BOT_WS_DIR
source $RLBOT_PKG_DIR/lib/.venv/bin/activate
source $RLBOT_WS_DIR/install/local_setup.bash
#cd $RLBOT_AGENT_DIR
